name: sample2

on:
  pull_request_target:

jobs:
  run-command:
    runs-on: ubuntu-latest
    env:
      PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
    steps:
      - name: Run the command
        run: |
          ./command.sh --token "$PROD_TOKEN"